Fix `ModalBuilder::setComponents`
`ModalBuilder::new` has typehint `ComponentObject[]` so that means array of them, but `setComponents` accepts variadic param and then after it calls `addComponent` an error is thrown

> TypeError: Discord\Builders\ModalBuilder::addComponent(): Argument #1 ($component) must be of type Discord\Builders\Components\ComponentObject, array given

Also `ModalBuilder::setComponents` has phpdoc with `ComponentObject[]` array so it contradicts with php variadic definition